% Make plot of phase average genesis density. 
%
% Run prep.m on individual phase's event dataset. Then run gendensity.m on
% that set, and save output: phs1_genDen = z; clearvars -except
% phs1_genDen; 
% Repeat for each phase of the MJO. 
%
% Meg D. Fowler, 25 July 2019 

%% Define arrays 

% Large array with genesis density in each phase
genDen_fullArr = nan(8,16,56);       % [phase, lat(y), lon(x)]              
genDen_fullArr(1,:,:) = phs1_genDen;
genDen_fullArr(2,:,:) = phs2_genDen;
genDen_fullArr(3,:,:) = phs3_genDen;
genDen_fullArr(4,:,:) = phs4_genDen;
genDen_fullArr(5,:,:) = phs5_genDen;
genDen_fullArr(6,:,:) = phs1_genDen;
genDen_fullArr(7,:,:) = phs7_genDen;
genDen_fullArr(8,:,:) = phs8_genDen;

%Phase average genesis density 
genDen_phsMean = squeeze(nanmean(genDen_fullArr,1));  

%% Need to compare with observations and GPI
%  Phase-average GPI generated by GPI_PhaseMean_Bootstrapped.m              ***[GPI_phsMean]***
%  Obs from runnin gendensitybesttrack.m --> enter "genDen_obs = z2;" after
%  running the obs program to save into new array.                          ***[genDen_obs]***

% Also need a fair of way doing this... look at mean or max
% meridional/zonally? 

%Define MIT model lon/lat
lon_model = x;
lat_model = y; 

lonMean_model = squeeze(nanmean(genDen_phsMean,2));
lonMax_model  = squeeze(nanmax(genDen_phsMean,[],2));
latMean_model = squeeze(nanmean(genDen_phsMean,1));
latMax_model  = squeeze(nanmax(genDen_phsMean,[],1)); 

lonMean_obs   = squeeze(nanmean(genDen_obs,2));
lonMax_obs    = squeeze(nanmax(genDen_obs,[],2));
latMean_obs   = squeeze(nanmean(genDen_obs,1));
latMax_obs    = squeeze(nanmax(genDen_obs,[],1)); 

%Limit GPI to same range and take mean/max 
%   NOTE: GPI has a resolution of 2.5deg instead of 2, so not quite the
%   same lat/lon 
minLon = find(lon==min(lon_model));
maxLon = find(lon==max(lon_model));
minLat = find(lat==max(lat_model));
maxLat = find(lat==min(lat_model));
lat_GPI     = lat(minLat:maxLat);
lon_GPI     = lon(minLon:maxLon);
GPI_region = GPI_phsMean(minLon:maxLon, minLat:maxLat)';

lonMean_GPI = squeeze(nanmean(GPI_region,2)); 
lonMax_GPI  = squeeze(nanmax(GPI_region,[],2));
latMean_GPI = squeeze(nanmean(GPI_region,1));
latMax_GPI  = squeeze(nanmax(GPI_region,[],1)); 

%% Might want to apply a 4-degree moving window to latMeans to smooth out the signal a bit
%  This would be a 5 degree moving window in GPI 

for iLon = 1:length(lon_model)
    if iLon==1
        smthLatMean_model(iLon) = latMean_model(1,iLon);
        smthLatMax_model(iLon)  = latMax_model(1,iLon);
        smthLatMean_obs(iLon)   = latMean_obs(1,iLon);
        smthLatMax_obs(iLon)    = latMax_obs(1,iLon); 
    else
       smthLatMean_model(iLon)  = nanmean(latMean_model(1,(iLon-1):iLon));
       smthLatMax_model(iLon)   = nanmean(latMax_model(1,(iLon-1):iLon));
       smthLatMean_obs(iLon)    = nanmean(latMean_obs(1,(iLon-1):iLon)); 
       smthLatMax_obs(iLon)     = nanmean(latMax_obs(1,(iLon-1):iLon));
    end
end

for iLon = 1:length(lon_GPI)
    if iLon==1 
        smthLatMean_GPI(iLon) = latMean_GPI(1,iLon);
        smthLatMax_GPI(iLon)  = latMax_GPI(1,iLon);
    else
        smthLatMean_GPI(iLon) = nanmean(latMean_GPI(1,(iLon-1):iLon));
        smthLatMax_GPI(iLon)  = nanmean(latMax_GPI(1,(iLon-1):iLon)); 
    end
end


%% Try some plotting

% ---- Longitudinal Mean Genesis Density and GPI --- % 
figure;
%Add Gen Density lines first 
h1 = plot(lonMean_obs, lat_model,'k','linewidth',2);    %OBS
hold on;
h2 = plot(lonMean_model, lat_model,'b','linewidth',2);  %MODEL
xlabel('Genesis Density')
ylabel('Latitude (degrees)')
title({'Longitudinal average genesis density and GPI'; ' '; ' '},'fontsize',20)
%Add GPI as new axis 
ax1 = gca; % current axes
ax1_pos = ax1.Position; % position of first axes
ax2 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
ax2.XColor = 'red';
ax2.YColor = 'red';
hold on;
%Plot GPI
h3 = plot(lonMean_GPI,lat_GPI,'r','Parent',ax2,'linewidth',2,'DisplayName','GPI');
xlabel('GPI anomaly');
ylabel('Latitude (degrees)');
legend([h1 h2 h3],'Best track', 'MIT model (Phase 1-8 average)', 'GPI anomaly');
grid on



% ---- Longitudinal MAX Genesis Density and GPI --- % 
figure;
%Add Gen Density lines first 
h1 = plot(lonMax_obs, lat_model,'k','linewidth',2);    %OBS
hold on;
h2 = plot(lonMax_model, lat_model,'b','linewidth',2);  %MODEL
xlabel('Genesis Density')
ylabel('Latitude (degrees)')
xlim([100 180]);
title({'Longitudinal maximum genesis density and GPI'; ' '; ' '},'fontsize',20)
%Add GPI as new axis 
ax1 = gca; % current axes
ax1_pos = ax1.Position; % position of first axes
ax2 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
ax2.XColor = 'red';
ax2.YColor = 'red';
hold on;
%Plot GPI
h3 = plot(lonMax_GPI,lat_GPI,'r','Parent',ax2,'linewidth',2,'DisplayName','GPI');
xlabel('GPI anomaly');
ylabel('Latitude (degrees)');
xlim([100 180]);
legend([h1 h2 h3],'Best track', 'MIT model (Phase 1-8 average)', 'GPI anomaly');


% ----------Latitudinal averages -----------------------------%


% ---- Latitudinal Mean Genesis Density and GPI --- % 
figure;
%Add Gen Density lines first 
h1 = plot(lon_model,smthLatMean_obs,'k','linewidth',2);    %OBS
hold on;
h2 = plot(lon_model,smthLatMean_model,'b','linewidth',2);  %MODEL
ylabel('Genesis Density')
xlabel('Longitude (degrees)')
xlim([100 180]);
title({'Latitudinal average genesis density and GPI'; ' '; ' '},'fontsize',20)
%Add GPI as new axis 
ax1 = gca; % current axes
ax1_pos = ax1.Position; % position of first axes
ax2 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
ax2.XColor = 'red';
ax2.YColor = 'red';
hold on;
%Plot GPI
h3 = plot(lon_GPI,smthLatMean_GPI,'r','Parent',ax2,'linewidth',2,'DisplayName','GPI');
ylabel('GPI anomaly');
xlabel('Longitude (degrees)');
xlim([100 180]);
legend([h1 h2 h3],'Best track', 'MIT model (Phase 1-8 average)', 'GPI anomaly');
grid on;

% ---- Latitudinal MAX Genesis Density and GPI --- % 
figure;
%Add Gen Density lines first 
h1 = plot(lon_model,smthLatMax_obs,'k','linewidth',2);    %OBS
hold on;
h2 = plot(lon_model,smthLatMax_model,'b','linewidth',2);  %MODEL
ylabel('Genesis Density')
xlabel('Longitude (degrees)')
xlim([100 180]);
title({'Latitudinal maximum genesis density and GPI'; ' '; ' '},'fontsize',20)
%Add GPI as new axis 
ax1 = gca; % current axes
ax1_pos = ax1.Position; % position of first axes
ax2 = axes('Position',ax1_pos,...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none');
ax2.XColor = 'red';
ax2.YColor = 'red';
hold on;
%Plot GPI
h3 = plot(lon_GPI,smthLatMax_GPI,'r','Parent',ax2,'linewidth',2,'DisplayName','GPI');
ylabel('GPI anomaly');
xlabel('Longitude (degrees)');
xlim([100 180]);
legend([h1 h2 h3],'Best track', 'MIT model (Phase 1-8 average)', 'GPI anomaly');
